#!/usr/bin/env python3
# AUTO-GENERATED by analytics_engine — 2026-03-19T19:34:02.156320
# Produces chart data JSONs for frontend interactive charts.

import pandas as pd
import json
from pathlib import Path

DATASET_PATHS = {
    "user_summary": "/Users/harshnahata/Desktop/gc26-master/data/datasets/combined_data(2025-3-1-2026-2-28) by user.csv",
    "monthly": "/Users/harshnahata/Desktop/gc26-master/data/datasets/monthly-chart.csv",
    "channel_user": "/Users/harshnahata/Desktop/gc26-master/data/datasets/combined_data(2025-3-1-2026-2-28) by channel and user.csv",
    "channel_platform": "/Users/harshnahata/Desktop/gc26-master/data/datasets/channel-wise-publishing.csv",
    "language": "/Users/harshnahata/Desktop/gc26-master/data/datasets/combined_data(2025-3-1-2026-2-28) by language.csv",
    "output_type": "/Users/harshnahata/Desktop/gc26-master/data/datasets/combined_data(2025-3-1-2026-2-28) by output type.csv",
    "input_type": "/Users/harshnahata/Desktop/gc26-master/data/datasets/combined_data(2025-3-1-2026-2-28) by input type.csv"
}
OUTPUT_DIR = Path('/Users/harshnahata/Desktop/gc26-master/data/chart_data')
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# ─── Column mappings ─────────────────────────────────────────────────────
CS_CHANNEL   = 'Channel'
CS_UPLOADED  = 'Uploaded Count'
CS_CREATED   = 'Created Count'
CS_PUBLISHED = 'Published Count'

MO_MONTH     = 'Month'
MO_UPLOADED  = 'Total Uploaded'
MO_CREATED   = 'Total Created'
MO_PUBLISHED = 'Total Published'

OT_NAME      = 'Output Type'
OT_CREATED   = 'Created Count'

IT_NAME      = 'Input Type'
IT_UPLOADED  = 'Uploaded Count'

CP_CHANNEL   = 'Channels'

OUTPUT_TYPE_COLORS = ["#4F46E5", "#06B6D4", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6", "#EC4899"]
INPUT_TYPE_COLORS = ["#4F46E5", "#06B6D4", "#10B981", "#F59E0B", "#EF4444", "#8B5CF6", "#EC4899", "#14B8A6", "#F97316", "#6366F1", "#D946EF", "#84CC16"]


def save_json(data, filename):
    path = OUTPUT_DIR / filename
    path.write_text(json.dumps(data, indent=2, default=str), encoding="utf-8")
    return str(path)


def generate_all_chart_data():
    results = {}

    # ─── Monthly Trends ───────────────────────────────────────────────
    mo_path = DATASET_PATHS.get("monthly")
    if mo_path and Path(mo_path).exists():
        df = pd.read_csv(mo_path, encoding="utf-8-sig")
        monthly_data = []
        for _, row in df.iterrows():
            upl = int(pd.to_numeric(row.get(MO_UPLOADED, 0), errors="coerce") or 0)
            cre = int(pd.to_numeric(row.get(MO_CREATED, 0), errors="coerce") or 0)
            pub = int(pd.to_numeric(row.get(MO_PUBLISHED, 0), errors="coerce") or 0)
            pr = round(pub / cre * 100, 2) if cre > 0 else 0
            month_str = str(row.get(MO_MONTH, "")).strip().strip('"')
            # Shorten month label for chart
            short_month = month_str.split(",")[0].strip() if "," in month_str else month_str
            monthly_data.append({
                "month": short_month,
                "uploaded": upl,
                "created": cre,
                "published": pub,
                "publishRate": pr
            })
        results["monthly_trends"] = monthly_data
        save_json(monthly_data, "monthly_trends.json")

    # ─── Channel Performance ──────────────────────────────────────────
    cs_path = DATASET_PATHS.get("channel_summary")
    if cs_path and Path(cs_path).exists():
        df = pd.read_csv(cs_path, encoding="utf-8-sig")
        channel_data = []
        for _, row in df.iterrows():
            upl = int(pd.to_numeric(row.get(CS_UPLOADED, 0), errors="coerce") or 0)
            cre = int(pd.to_numeric(row.get(CS_CREATED, 0), errors="coerce") or 0)
            pub = int(pd.to_numeric(row.get(CS_PUBLISHED, 0), errors="coerce") or 0)
            rate = round(pub / cre * 100, 2) if cre > 0 else 0
            amp = round(cre / upl, 2) if upl > 0 else 0
            channel_data.append({
                "name": f"Channel {row.get(CS_CHANNEL, '')}",
                "uploaded": upl,
                "created": cre,
                "published": pub,
                "rate": rate,
                "amp": amp
            })
        # Sort by uploaded desc, take top channels
        channel_data.sort(key=lambda x: x["uploaded"], reverse=True)
        results["channel_performance"] = channel_data
        save_json(channel_data, "channel_performance.json")

        # ─── Funnel Data ──────────────────────────────────────────────
        total_upl = sum(c["uploaded"] for c in channel_data)
        total_cre = sum(c["created"] for c in channel_data)
        total_pub = sum(c["published"] for c in channel_data)
        funnel = [
            {"stage": "Uploaded", "value": total_upl},
            {"stage": "Processed", "value": total_cre},
            {"stage": "Published", "value": total_pub}
        ]
        results["funnel_data"] = funnel
        save_json(funnel, "funnel_data.json")

    # ─── Output Type Mix ──────────────────────────────────────────────
    ot_path = DATASET_PATHS.get("output_type")
    if ot_path and Path(ot_path).exists():
        df = pd.read_csv(ot_path, encoding="utf-8-sig")
        ot_data = []
        for i, (_, row) in enumerate(df.iterrows()):
            val = int(pd.to_numeric(row.get(OT_CREATED, 0), errors="coerce") or 0)
            ot_data.append({
                "name": str(row.get(OT_NAME, "")).strip().strip('"'),
                "value": val,
                "color": OUTPUT_TYPE_COLORS[i % len(OUTPUT_TYPE_COLORS)]
            })
        ot_data.sort(key=lambda x: x["value"], reverse=True)
        results["output_type_mix"] = ot_data
        save_json(ot_data, "output_type_mix.json")

    # ─── Input Type Mix ───────────────────────────────────────────────
    it_path = DATASET_PATHS.get("input_type")
    if it_path and Path(it_path).exists():
        df = pd.read_csv(it_path, encoding="utf-8-sig")
        it_data = []
        for i, (_, row) in enumerate(df.iterrows()):
            val = int(pd.to_numeric(row.get(IT_UPLOADED, 0), errors="coerce") or 0)
            it_data.append({
                "name": str(row.get(IT_NAME, "")).strip().strip('"'),
                "value": val,
                "color": INPUT_TYPE_COLORS[i % len(INPUT_TYPE_COLORS)]
            })
        it_data.sort(key=lambda x: x["value"], reverse=True)
        results["input_type_mix"] = it_data
        save_json(it_data, "input_type_mix.json")

    # ─── Platform Distribution ────────────────────────────────────────
    cp_path = DATASET_PATHS.get("channel_platform")
    if cp_path and Path(cp_path).exists():
        df = pd.read_csv(cp_path, encoding="utf-8-sig")
        # Sum across all channels for each platform
        platform_cols = [c for c in df.columns if c != CP_CHANNEL]
        platform_data = []
        for col in platform_cols:
            total = int(pd.to_numeric(df[col], errors="coerce").sum())
            if total > 0:
                platform_data.append({"name": col, "value": total})
        platform_data.sort(key=lambda x: x["value"], reverse=True)
        results["platform_distribution"] = platform_data
        save_json(platform_data, "platform_distribution.json")

    return results


if __name__ == "__main__":
    result = generate_all_chart_data()
    print(json.dumps({k: len(v) for k, v in result.items()}, indent=2))
