#!/usr/bin/env python3
# AUTO-GENERATED by analytics_engine — 2026-03-21T03:27:20.355612
# Column mappings baked in from column_mapper. Reused on data-append runs.
# DO NOT EDIT column assignments manually — regenerated on schema change.

import pandas as pd
import json
from pathlib import Path

# ─── Dataset paths ───────────────────────────────────────────────────────
DATASET_PATHS = {
    "channel_platform": "/home/vk_lx/Desktop/frammer_agent/data/datasets/channel-wise-publishing.csv",
    "monthly": "/home/vk_lx/Desktop/frammer_agent/data/datasets/monthly-chart.csv",
    "output_type": "/home/vk_lx/Desktop/frammer_agent/data/datasets/combined_data(2025-3-1-2026-2-28) by output type.csv",
    "channel_user": "/home/vk_lx/Desktop/frammer_agent/data/datasets/combined_data(2025-3-1-2026-2-28) by channel and user.csv",
    "language": "/home/vk_lx/Desktop/frammer_agent/data/datasets/combined_data(2025-3-1-2026-2-28) by language.csv",
    "user_summary": "/home/vk_lx/Desktop/frammer_agent/data/datasets/combined_data(2025-3-1-2026-2-28) by user.csv",
    "input_type": "/home/vk_lx/Desktop/frammer_agent/data/datasets/combined_data(2025-3-1-2026-2-28) by input type.csv"
}

# ─── Column mappings (auto-generated) ────────────────────────────────────
# channel_summary columns
CS_CHANNEL   = 'Channel'
CS_UPLOADED  = 'Uploaded Count'
CS_CREATED   = 'Created Count'
CS_PUBLISHED = 'Published Count'
CS_UPL_DUR   = 'Uploaded Duration (hh:mm:ss)'
CS_CRE_DUR   = 'Created Duration (hh:mm:ss)'
CS_PUB_DUR   = 'Published Duration (hh:mm:ss)'

# monthly columns
MO_MONTH     = 'Month'
MO_UPLOADED  = 'Total Uploaded'
MO_CREATED   = 'Total Created'
MO_PUBLISHED = 'Total Published'

# user_summary columns
US_USER      = 'User'

# channel_user columns
CU_CHANNEL   = 'Channel'
CU_USER      = 'User'


def parse_duration_to_seconds(series):
    """Parse hh:mm:ss strings to total seconds. Handles hours > 99."""
    def _parse(s):
        try:
            s = str(s).strip()
            if not s or s == "nan":
                return 0
            parts = s.split(":")
            if len(parts) == 3:
                return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(parts[2])
            elif len(parts) == 2:
                return int(parts[0]) * 60 + int(parts[1])
            return 0
        except Exception:
            return 0
    return series.apply(_parse)


def compute_kpis():
    """Compute all KPI metrics. Returns dict of metrics."""
    metrics = []

    # ─── Load channel_summary ─────────────────────────────────────────
    cs_path = DATASET_PATHS.get("channel_summary")
    if cs_path and Path(cs_path).exists():
        df = pd.read_csv(cs_path, encoding="utf-8-sig")

        # Volume KPIs
        total_uploaded = int(pd.to_numeric(df[CS_UPLOADED], errors="coerce").sum())
        total_processed = int(pd.to_numeric(df[CS_CREATED], errors="coerce").sum())
        total_published = int(pd.to_numeric(df[CS_PUBLISHED], errors="coerce").sum())

        metrics.append({"id": "total_uploaded",  "name": "Total Uploaded",  "value": total_uploaded,
                         "formatted": f"{total_uploaded:,}", "category": "volume",
                         "description": "Total videos uploaded by users"})
        metrics.append({"id": "total_processed", "name": "Total Processed", "value": total_processed,
                         "formatted": f"{total_processed:,}", "category": "volume",
                         "description": "Total clips created by AI"})
        metrics.append({"id": "total_published", "name": "Total Published", "value": total_published,
                         "formatted": f"{total_published:,}", "category": "volume",
                         "description": "Total clips published to platforms"})

        # Conversion KPIs
        publish_rate = round((total_published / total_processed * 100), 2) if total_processed > 0 else 0
        metrics.append({"id": "publish_rate", "name": "Publish Rate", "value": publish_rate,
                         "formatted": f"{publish_rate}%", "category": "conversion",
                         "description": "Percentage of processed clips published"})

        # Efficiency KPIs
        amplification = round(total_processed / total_uploaded, 2) if total_uploaded > 0 else 0
        process_rate = round(total_processed / total_uploaded * 100, 2) if total_uploaded > 0 else 0
        metrics.append({"id": "amplification_ratio", "name": "Amplification Ratio", "value": amplification,
                         "formatted": f"{amplification}x", "category": "efficiency",
                         "description": "Output clips per uploaded video"})
        metrics.append({"id": "process_rate", "name": "Process Rate", "value": process_rate,
                         "formatted": f"{process_rate}%", "category": "efficiency",
                         "description": "Processing rate per upload"})

        # Duration KPIs
        upl_seconds = parse_duration_to_seconds(df[CS_UPL_DUR]).sum()
        cre_seconds = parse_duration_to_seconds(df[CS_CRE_DUR]).sum()
        pub_seconds = parse_duration_to_seconds(df[CS_PUB_DUR]).sum()
        uploaded_hours = round(upl_seconds / 3600, 2)
        processed_hours = round(cre_seconds / 3600, 2)
        published_hours = round(pub_seconds / 3600, 2)
        avg_upload_min = round(upl_seconds / total_uploaded / 60, 2) if total_uploaded > 0 else 0

        metrics.append({"id": "uploaded_hours", "name": "Uploaded Hours", "value": uploaded_hours,
                         "formatted": f"{uploaded_hours}h", "category": "duration",
                         "description": "Total duration of uploaded videos"})
        metrics.append({"id": "processed_hours", "name": "Processed Hours", "value": processed_hours,
                         "formatted": f"{processed_hours}h", "category": "duration",
                         "description": "Total duration of processed clips"})
        metrics.append({"id": "published_hours", "name": "Published Hours", "value": published_hours,
                         "formatted": f"{published_hours}h", "category": "duration",
                         "description": "Total duration of published clips"})
        metrics.append({"id": "avg_upload_min", "name": "Avg Upload Duration", "value": avg_upload_min,
                         "formatted": f"{avg_upload_min} min", "category": "duration",
                         "description": "Average duration per uploaded video"})

        # Distinct channels
        distinct_channels = int(df[CS_CHANNEL].nunique())
        metrics.append({"id": "distinct_channels", "name": "Distinct Channels", "value": distinct_channels,
                         "formatted": str(distinct_channels), "category": "volume",
                         "description": "Number of unique channels"})

        # Top performing channel
        df_c = df.copy()
        df_c["_created_num"] = pd.to_numeric(df_c[CS_CREATED], errors="coerce")
        df_c["_published_num"] = pd.to_numeric(df_c[CS_PUBLISHED], errors="coerce")
        df_c["_pr"] = df_c["_published_num"] / df_c["_created_num"].replace(0, float("nan"))
        valid = df_c.dropna(subset=["_pr"])
        if len(valid) > 0:
            top_row = valid.loc[valid["_pr"].idxmax()]
            top_ch = str(top_row[CS_CHANNEL])
            top_rate = round(float(top_row["_pr"] * 100), 2)
            metrics.append({"id": "top_performing_channel", "name": "Top Channel", "value": top_ch,
                             "formatted": f"{top_ch} ({top_rate}%)", "category": "conversion",
                             "description": "Channel with highest publish rate"})

    # ─── Load user_summary for distinct users ─────────────────────────
    us_path = DATASET_PATHS.get("user_summary")
    if us_path and Path(us_path).exists():
        df_u = pd.read_csv(us_path, encoding="utf-8-sig")
        distinct_users = int(df_u[US_USER].nunique())
        metrics.append({"id": "distinct_users", "name": "Distinct Users", "value": distinct_users,
                         "formatted": str(distinct_users), "category": "volume",
                         "description": "Number of unique users"})

    # ─── Load monthly for peak month ──────────────────────────────────
    mo_path = DATASET_PATHS.get("monthly")
    if mo_path and Path(mo_path).exists():
        df_m = pd.read_csv(mo_path, encoding="utf-8-sig")
        df_m["_upl_num"] = pd.to_numeric(df_m[MO_UPLOADED], errors="coerce")
        if len(df_m) > 0 and df_m["_upl_num"].sum() > 0:
            peak_row = df_m.loc[df_m["_upl_num"].idxmax()]
            peak_month = str(peak_row[MO_MONTH])
            peak_count = int(peak_row["_upl_num"])
            metrics.append({"id": "peak_upload_month", "name": "Peak Upload Month", "value": peak_month,
                             "formatted": f"{peak_month} ({peak_count:,})", "category": "efficiency",
                             "description": "Month with highest upload volume"})

    return metrics


if __name__ == "__main__":
    result = compute_kpis()
    print(json.dumps(result, indent=2, default=str))
